#!/bin/bash

#Enable test repo
echo deb http://meshwithme.online/deb/repos/apt/debian stretch main | sudo tee /etc/apt/sources.list.d/tomesh.list

sudo apt-get update
sudo apt-get install babeld-tomesh
sudo systemctl restart babeld
