#!/bin/bash

#NOTE
# if running outside new develop branch you require to add an ip address 
# add
# sudo ifconfig $mesh_dev $(confget -f /etc/mesh.conf -s general "ipv4")
# when you see the comments "# Optionally assign IPv4 address to the mesh_dev interface"

#Enable test repo
echo deb http://meshwithme.online/deb/repos/apt/debian stretch main | sudo tee /etc/apt/sources.list.d/tomesh.list

sudo apt-get update
sudo apt-get install babeld-tomesh
sudo systemctl restart babeld
